[package]
name = "client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
rand="0.8.4"
base64="0.13.0"

[dependencies.xorcrypt]
path="../xorcrypt"